import { BussinessI, ReviewI } from "./Types/Businesses.types";

export const reviews: ReviewI[] = [
  {
    _id: "r1",
    title: "Great Service",
    description: "Excellent service and friendly staff.",
    username: "user1",
    userID: "u1",
    rating: 5,
    bussiness: "b1",
    likes: 5,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    _id: "r2",
    title: "Good Quality",
    description: "High-quality products and quick delivery.",
    username: "user2",
    userID: "u2",
    rating: 4,
    bussiness: "b2",
    likes: 3,
    createdAt: "2024-01-02T00:00:00Z",
  },
  {
    _id: "r3",
    title: "Very Satisfied",
    description: "I am very satisfied with my purchase.",
    username: "Eden",
    userID: "u3",
    rating: 5,
    bussiness: "b3",
    likes: 8,
    createdAt: "2024-01-03T00:00:00Z",
  },
  {
    _id: "r4",
    title: "Could Be Better",
    description: "The service could be improved.",
    username: "user4",
    userID: "u4",
    rating: 3,
    bussiness: "b4",
    likes: 2,
    createdAt: "2024-01-04T00:00:00Z",
  },
  {
    _id: "r5",
    title: "Excellent",
    description: "Fantastic experience from start to finish.",
    username: "user5",
    userID: "u5",
    rating: 5,
    bussiness: "b5",
    likes: 7,
    createdAt: "2024-01-05T00:00:00Z",
  },
  {
    _id: "r6",
    title: "Not Happy",
    description: "I am not happy with the service.",
    username: "user6",
    userID: "u6",
    rating: 2,
    bussiness: "b6",
    likes: 1,
    createdAt: "2024-01-06T00:00:00Z",
  },
  {
    _id: "r7",
    title: "Good Support",
    description: "Great customer support and follow-up.",
    username: "user7",
    userID: "u7",
    rating: 4,
    bussiness: "b7",
    likes: 4,
    createdAt: "2024-01-07T00:00:00Z",
  },
  {
    _id: "r8",
    title: "Love It",
    description: "I love this place, will visit again.",
    username: "user8",
    userID: "u8",
    rating: 5,
    bussiness: "b8",
    likes: 6,
    createdAt: "2024-01-08T00:00:00Z",
  },
  {
    _id: "r9",
    title: "Highly Recommend",
    description: "I highly recommend this business.",
    username: "user9",
    userID: "u9",
    rating: 5,
    bussiness: "b1",
    likes: 9,
    createdAt: "2024-01-09T00:00:00Z",
  },
  {
    _id: "r10",
    title: "Just Okay",
    description: "The service was just okay.",
    username: "user10",
    userID: "u10",
    rating: 3,
    bussiness: "b2",
    likes: 2,
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    _id: "r11",
    title: "Superb Experience",
    description: "I had a superb experience with this business.",
    username: "user11",
    userID: "u11",
    rating: 5,
    bussiness: "b1",
    likes: 10,
    createdAt: "2024-01-11T00:00:00Z",
  },
  {
    _id: "r12",
    title: "Not Worth It",
    description: "The service is not worth the price.",
    username: "user12",
    userID: "u12",
    rating: 1,
    bussiness: "b3",
    likes: 0,
    createdAt: "2024-01-12T00:00:00Z",
  },
];

function calculateAverageRating(reviews: ReviewI[]): number {
  const totalRating = reviews.reduce((sum, review) => sum + review.rating, 0);
  return reviews.length ? totalRating / reviews.length : 0;
}

export const businesses: BussinessI[] = [
  {
    _id: "b1",
    name: "Tech Innovators",
    about: "Leading the way in tech innovation and software solutions.",
    reviews: reviews.filter((review) => review.bussiness === "b1"),
    categories: "Technology",
    avgRating: calculateAverageRating(
      reviews.filter((review) => review.bussiness === "b1")
    ),
    phone: "123-456-7890",
    email: "info@techinnovators.com",
    district: "Downtown",
    city: "San Francisco",
    street: "123 Market St",
  },
  {
    _id: "b2",
    name: "Green Thumb",
    about: "Providing the best in gardening supplies and advice.",
    reviews: reviews.filter((review) => review.bussiness === "b2"),
    categories: "Gardening",
    avgRating: calculateAverageRating(
      reviews.filter((review) => review.bussiness === "b2")
    ),
    phone: "987-654-3210",
    email: "contact@greenthumb.com",
    district: "West End",
    city: "Los Angeles",
    street: "456 Sunset Blvd",
  },
  {
    _id: "b3",
    name: "Healthy Eats",
    about: "Delivering fresh and healthy meals to your doorstep.",
    reviews: reviews.filter((review) => review.bussiness === "b3"),
    categories: "Food Delivery",
    avgRating: calculateAverageRating(
      reviews.filter((review) => review.bussiness === "b3")
    ),
    phone: "555-123-4567",
    email: "support@healthyeats.com",
    district: "Midtown",
    city: "New York",
    street: "789 Broadway",
  },
  {
    _id: "b4",
    name: "Fitness First",
    about: "Your go-to place for fitness and wellness.",
    reviews: reviews.filter((review) => review.bussiness === "b4"),
    categories: "Fitness",
    avgRating: calculateAverageRating(
      reviews.filter((review) => review.bussiness === "b4")
    ),
    phone: "444-555-6666",
    email: "hello@fitnessfirst.com",
    district: "Uptown",
    city: "Chicago",
    street: "101 State St",
  },
  {
    _id: "b5",
    name: "Fashion Forward",
    about: "Trendy and affordable fashion for everyone.",
    reviews: reviews.filter((review) => review.bussiness === "b5"),
    categories: "Fashion",
    avgRating: calculateAverageRating(
      reviews.filter((review) => review.bussiness === "b5")
    ),
    phone: "333-777-8888",
    email: "info@fashionforward.com",
    district: "SoHo",
    city: "New York",
    street: "202 Spring St",
  },
  {
    _id: "b6",
    name: "Book Haven",
    about: "A paradise for book lovers.",
    reviews: reviews.filter((review) => review.bussiness === "b6"),
    categories: "Books",
    avgRating: calculateAverageRating(
      reviews.filter((review) => review.bussiness === "b6")
    ),
    phone: "222-999-0000",
    email: "contact@bookhaven.com",
    district: "Historic District",
    city: "Boston",
    street: "303 Beacon St",
  },
  {
    _id: "b7",
    name: "Artisan Crafts",
    about: "Handmade crafts and artisanal goods.",
    reviews: reviews.filter((review) => review.bussiness === "b7"),
    categories: "Crafts",
    avgRating: calculateAverageRating(
      reviews.filter((review) => review.bussiness === "b7")
    ),
    phone: "111-222-3333",
    email: "support@artisancrafts.com",
    district: "Arts District",
    city: "Portland",
    street: "404 NW 10th Ave",
  },
  {
    _id: "b8",
    name: "Pet Paradise",
    about: "Everything you need for your furry friends.",
    reviews: reviews.filter((review) => review.bussiness === "b8"),
    categories: "Pet Supplies",
    avgRating: calculateAverageRating(
      reviews.filter((review) => review.bussiness === "b8")
    ),
    phone: "666-444-1111",
    email: "hello@petparadise.com",
    district: "Suburban",
    city: "Seattle",
    street: "505 Pet St",
  },
];
