export const reviews = [
  {
    _id: "r1",
    title: "Great Service",
    description: "Excellent service and friendly staff.",
    username: "user1",
    userID: "u1",
    bussiness: "b1",
    likes: 5,
  },
  {
    _id: "r2",
    title: "Good Quality",
    description: "High-quality products and quick delivery.",
    username: "user2",
    userID: "u2",
    bussiness: "b2",
    likes: 3,
  },
  {
    _id: "r3",
    title: "Very Satisfied",
    description: "I am very satisfied with my purchase.",
    username: "Eden",
    userID: "u3",
    bussiness: "b3",
    likes: 8,
  },
  {
    _id: "r4",
    title: "Could Be Better",
    description: "The service could be improved.",
    username: "user4",
    userID: "u4",
    bussiness: "b4",
    likes: 2,
  },
  {
    _id: "r5",
    title: "Excellent",
    description: "Fantastic experience from start to finish.",
    username: "user5",
    userID: "u5",
    bussiness: "b5",
    likes: 7,
  },
  {
    _id: "r6",
    title: "Not Happy",
    description: "I am not happy with the service.",
    username: "user6",
    userID: "u6",
    bussiness: "b6",
    likes: 1,
  },
  {
    _id: "r7",
    title: "Good Support",
    description: "Great customer support and follow-up.",
    username: "user7",
    userID: "u7",
    bussiness: "b7",
    likes: 4,
  },
  {
    _id: "r8",
    title: "Love It",
    description: "I love this place, will visit again.",
    username: "user8",
    userID: "u8",
    bussiness: "b8",
    likes: 6,
  },
  {
    _id: "r9",
    title: "Highly Recommend",
    description: "I highly recommend this business.",
    username: "user9",
    userID: "u9",
    bussiness: "b1",
    likes: 9,
  },
  {
    _id: "r10",
    title: "Just Okay",
    description: "The service was just okay.",
    username: "user10",
    userID: "u10",
    bussiness: "b2",
    likes: 2,
  },
];

export const businesses = [
  {
    _id: "b1",
    name: "Tech Innovators",
    about: "Leading the way in tech innovation and software solutions.",
    reviews: reviews.filter((review) => review.bussiness === "b1"),
    contact: {
      phone: "123-456-7890",
      email: "info@techinnovators.com",
    },
    location: {
      district: "Downtown",
      city: "San Francisco",
      street: "123 Market St",
    },
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    _id: "b2",
    name: "Green Thumb",
    about: "Providing the best in gardening supplies and advice.",
    reviews: reviews.filter((review) => review.bussiness === "b2"),
    contact: {
      phone: "987-654-3210",
      email: "contact@greenthumb.com",
    },
    location: {
      district: "West End",
      city: "Los Angeles",
      street: "456 Sunset Blvd",
    },
    createdAt: "2023-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    _id: "b3",
    name: "Healthy Eats",
    about: "Delivering fresh and healthy meals to your doorstep.",
    reviews: reviews.filter((review) => review.bussiness === "b3"),
    contact: {
      phone: "555-123-4567",
      email: "support@healthyeats.com",
    },
    location: {
      district: "Midtown",
      city: "New York",
      street: "789 Broadway",
    },
    createdAt: "2023-03-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
  {
    _id: "b4",
    name: "Fitness First",
    about: "Your go-to place for fitness and wellness.",
    reviews: reviews.filter((review) => review.bussiness === "b4"),
    contact: {
      phone: "444-555-6666",
      email: "hello@fitnessfirst.com",
    },
    location: {
      district: "Uptown",
      city: "Chicago",
      street: "101 State St",
    },
    createdAt: "2023-04-01T00:00:00Z",
    updatedAt: "2024-04-01T00:00:00Z",
  },
  {
    _id: "b5",
    name: "Fashion Forward",
    about: "Trendy and affordable fashion for everyone.",
    reviews: reviews.filter((review) => review.bussiness === "b5"),
    contact: {
      phone: "333-777-8888",
      email: "info@fashionforward.com",
    },
    location: {
      district: "SoHo",
      city: "New York",
      street: "202 Spring St",
    },
    createdAt: "2023-05-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    _id: "b6",
    name: "Book Haven",
    about: "A paradise for book lovers.",
    reviews: reviews.filter((review) => review.bussiness === "b6"),
    contact: {
      phone: "222-999-0000",
      email: "contact@bookhaven.com",
    },
    location: {
      district: "Historic District",
      city: "Boston",
      street: "303 Beacon St",
    },
    createdAt: "2023-06-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    _id: "b7",
    name: "Artisan Crafts",
    about: "Handmade crafts and artisanal goods.",
    reviews: reviews.filter((review) => review.bussiness === "b7"),
    contact: {
      phone: "111-222-3333",
      email: "support@artisancrafts.com",
    },
    location: {
      district: "Arts District",
      city: "Portland",
      street: "404 NW 10th Ave",
    },
    createdAt: "2023-07-01T00:00:00Z",
    updatedAt: "2024-07-01T00:00:00Z",
  },
  {
    _id: "b8",
    name: "Pet Paradise",
    about: "Everything you need for your furry friends.",
    reviews: reviews.filter((review) => review.bussiness === "b8"),
    contact: {
      phone: "666-444-1111",
      email: "hello@petparadise.com",
    },
    location: {
      district: "Suburban",
      city: "Seattle",
      street: "505 Pet St",
    },
    createdAt: "2023-08-01T00:00:00Z",
    updatedAt: "2024-08-01T00:00:00Z",
  },
];
